### PR TITLE
Add integration tests and fix bad behavior of configuration file

### LINKED ISSUE #33: Bad behavior with configuration file
The configuration file is running with all available patterns instead of the specified due to reading it in the wrong path.

### PR DESCRIPTION
**Pull request by ljmf00**
Fixes #33

### CODE REVIEW

File: src/Analyzer/CodeAnalyzer.cs [hunk 1]
```diff
@@ -89,7 +91,8 @@ private void Dispose(bool disposing)
             }
 
             // delete created temporary directory
-            Directory.Delete(tmpSonarLintFolder, true);
+            if(tmpSonarLintFolder != null)
```
Comment (gjsduarte) [inline src/Analyzer/CodeAnalyzer.cs]: Codacy Issue found: [Add curly braces around the nested statement(s) in this 'if' block.](https://app.codacy.com/app/Codacy/codacy-sonar-csharp/pullRequest?prid=4528542)

File: .circleci/config.yml [hunk 2]
```diff
@@ -2,7 +2,7 @@ version: 2.1
 
 orbs:
   codacy: codacy/base@1.0.0
-  codacy_plugins_test: codacy/plugins-test@0.4.0
+  codacy_plugins_test: codacy/plugins-test@0.6.0
```
Comment (lolgab) [inline .circleci/config.yml]: Bump to 0.6.1 here

Comment (ljmf00) [reply .circleci/config.yml]: Done
