### PR TITLE
Fix usage of tool config file and parameters

### LINKED ISSUE #15: Can't change the parameters on the UI and bad behavior about config file
Temporary config file should be with the same name, otherwise parameters don't work.

Also, the logic about the config file is not working properly. When patterns exists on `.codacyrc`, should ignore tool config file, except if the user request it.

### PR DESCRIPTION
**Pull request by ljmf00**
Fixes #15 

I also added some tests to test the tool parameters.

### CODE REVIEW

File: src/Analyzer/CodeAnalyzer.cs [hunk 1]
```diff
@@ -60,6 +58,11 @@ public CodeAnalyzer() : base(csharpExtension)
 
                 new XDocument(new XElement("AnalysisInput", rules)).Save(tmpSonarLintPath);
                 additionalFiles.Add(new AnalyzerAdditionalFile(tmpSonarLintPath));
+            } else {
```
Comment (bmbferreira) [inline src/Analyzer/CodeAnalyzer.cs]:
```suggested
} else if (File.Exists(defaultSonarConfiguration)) {
```
